import {expect} from 'chai'
import Generate, {Props} from '.'

const props: Props = {
  timestamp: 'now',
  packages: [{
    source: 'export default 42',
    info: {
      name: 'answer',
      version: '42.0.0'
    }
  }, {
    source: 'export default 21',
    info: {
      name: 'half-answer',
      version: '21.0.0'
    }
  }]
}

// language=ts
const result = `
// generated by lit-doc
// time: now

import * as p0 from 'answer'
import * as p1 from 'half-answer'

export default {
  'answer': {
    exports: p0,
    source: "export default 42",
    info: {"name":"answer","version":"42.0.0"}
  },
  'half-answer': {
    exports: p1,
    source: "export default 21",
    info: {"name":"half-answer","version":"21.0.0"}
  }
}
`

it('generates the module file as expected', () => {
  expect(Generate(props)).eqls(result)
})
