export type Props = {
  timestamp: string
  packages: {
    source: string
    info: {
      name: string
      version: string
    }
  }[]
}

// language=ts
export default ({
  packages,
  timestamp
}: Props) => `
// generated by lit-doc
// time: ${timestamp}

${packages.map(({info}, i) => `
import * as p${i} from '${info.name}'
`.trim()).join('\n')}

export default {
  ${packages.map(({source, info}, i) => `
  '${info.name}': {
    exports: p${i},
    source: ${JSON.stringify(source)},
    info: ${JSON.stringify(info)}
  }`).join(',').trim()}
}
`
